//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBForTestEntities : DbContext
    {
        public DBForTestEntities()
            : base("name=DBForTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<apacct> apaccts { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Price_info> Price_info { get; set; }
        public virtual DbSet<Product_info> Product_info { get; set; }
        public virtual DbSet<Student> Students { get; set; }
    }
}
